### ISSUE TITLE
Can not run pip-review on Windows with Python 3

### ISSUE THREAD

**Issue by Kristinita** [jgonggrijp/pip-review#12]
### Summary

I can not run command `pip-review`.

### Expected behavior

I want automatically updates all my pip modules.

### Actual behavior

    E:\Chocolatey>pip-review
    "pip-review" не является внутренней или внешней
    командой, исполняемой программой или пакетным файлом.

### Steps to reproduce

I read in [Stack Overflow answer](http://stackoverflow.com/a/16269635/5951529), what I can update all my pip modules use `pip-review`. I install `pip-review` — `pip install pip-review`, I restart my Windows → I run `pip-review`, but I get error.

### Environment

**Operating system and version:**
Windows 10.0.14393
**Python**
3.5.2
**Pip**
8.1.2
**Pip-review**
0.4

Thanks.

**Comment by jgonggrijp** [comment]
Hello Kristina,

While it seems to work in most cases, pip-review is not officially supported under Python 3. In addition, I received some reports that pip-review does not work under Windows. I will fix these issues eventually, but I cannot promise it will happen soon.

Sorry for the disappointment. Until `pip-review` works for your setup, these are your options:

  - In order to **list all packages that can be upgraded**, run `pip list -o`.
  - In order to **upgrade selected packages and their dependencies**, run `pip install -U package other_package ...`.
  - In order to **upgrade all required packages in a virtual environment**, first `pip install pip-tools`. Make sure that you have a `requirements.in` file which has the names of the packages that are directly used by your project, each on a separate line, *without* pinned version numbers. Now, while your virtual environment is activated, run `pip-compile -U`. This will generate a `requirements.txt` which has your project requirements and all their dependencies with their versions pinned to the latest available, without actually updating anything. Finally, either run `pip install -U -r requirements.txt` or `pip-sync`. The former will upgrade all required packages and their depencies, but it will not remove packages that your doesn't depend on anymore. The latter will also upgrade all required packages and their dependencies *and* it will remove packages that your project doesn't depend on anymore, *but* it will also uninstall packages that you installed separately while your project never depended on them. Unfortunately, neither of these options will upgrade packages that your project doesn't depend on.

If I can help you with anything in the meanwhile, please let me know.

**Comment by jgonggrijp** [comment]
Actually, I found a way that should fix this. Please `pip install -U pip-review` to [version 0.5](https://pypi.python.org/pypi/pip-review/0.5) and let me know whether your issue is resolved. :-)

**Comment by jgonggrijp** [comment]
@Kristinita Did you see the update?

**Comment by Kristinita** [comment]
@jgonggrijp , thanks, now `pip-review` normally worked for me!
