### ISSUE TITLE
broken on local installed package

### ISSUE THREAD

**Issue by rachmadaniHaryono** [jgonggrijp/pip-review#49]
how to recreate the bug;

- install package from local folder.
- run pip-review (i run this way `python3 -m pip_review)
- pip-review report error and and paused indefinitely. user have to press `ctrl-c` to stop the program. see below for error message.

pip-review version  0.5.3 (no `pip-review --version`?) on .Python 3.5.2+ 

Linux q-N-a 4.7.10-040710-generic #201610220847 SMP Sat Oct 22 13:04:07 UTC 2016 i686 i686 i686 GNU/Linux

error message: 

```
Error when trying to get requirement for VCS system Command "git config --get-regexp remote\..*\.url" failed with error code 1 in /home/my_username/Downloads/my_python_module, falling back to uneditable format
Could not determine repository location of /home/my_username/Downloads/my_python_module
```

the folder is exist and can be accessed.

**Comment by jgonggrijp** [comment]
What do you mean by "install package from local folder"? Did you run `python setup.py install` or ` pip install .` or something else?
What is the output of `which python3`?

Have you generated an `.egg-info` file in your project directory? In that case, you are probably running into the problem that `pip freeze` is treating your module as an editable package, which breaks because it isn't associated with a VCS repo. Removing the `.egg-info` should solve the problem in that case. See also #21.

**Comment by rachmadaniHaryono** [comment]
>What do you mean by "install package from local folder"? 

>Did you run python setup.py install or pip install . or something else?

i run `pip install -e .` on local folder.

>What is the output of which python3?

    /usr/bin/python3

>Have you generated an .egg-info file in your project directory? 

yes

>Removing the .egg-info should solve the problem in that case

it did. thanks

**Comment by jgonggrijp** [comment]
For completeness: work is in progress to stop using `pip freeze` (see #32 and #41). When that is out, this catch with the local `.egg-info` might be eliminated, although I'm not completely sure what to expect yet.
