### ISSUE TITLE
Pip-review command not found 

### ISSUE THREAD

**Issue by Jacksole** [jgonggrijp/pip-review#83]
I recently found this pip-review tool. 

I see that build is failing but I installed it anyway, as I'm not a maintainer I don't know what is failiing but failing when I attempt to use the tool, I get this message pip-review: command not found.  I'm using Python 3.6.9 on WSL Ubuntu. The tool worked a few days ago, so if this tool isn't currently working.  @jgonggrijp

**Comment by jgonggrijp** [comment]
The Travis build is not failing in a serious way, though. Our test suite is very sensitive to the exact output given by the program. In Python <3.5, this output includes a warning about the Python version being obsolete, which trips up the test. If you push the "build failing" button, you will see that the tests actually pass in Python 3.6. So it is a problem with the test suite rather than with the program. See also #40, #61 and #69. 

The problem you describe sounds like an issue with your PATH environment variable. Did you perhaps install pip-review in a virtualenv and forget to activate that virtualenv the second time you wanted to use pip-review?

**Comment by Jacksole** [comment]
No, I just did a standard pip install. No virtual enviroments

**Comment by jgonggrijp** [comment]
Strange. If you do `pip list`, does the list still include `pip-review`?

**Comment by Jacksole** [comment]
Ok so it's listed so I see me all set now

**Comment by yohanelly95** [comment]
> Strange. If you do `pip list`, does the list still include `pip-review`?

I see it in pip-list, still does not work keeps saying `zsh: command not found: pip-review`

**Comment by jgonggrijp** [comment]
@yohanelly95 If you run the following command in the same environment where you run `pip list` (and where `pip-review` is not found), it will tell you the directory in which `pip-review` should be installed:

```sh
python -c 'import sys; import os.path as op; print(op.normpath(op.join(sys.prefix, "bin")))'
```

You can double-check that `pip-review` is in there:

```sh
ls $(python -c 'import sys; import os.path as op; print(op.normpath(op.join(sys.prefix, "bin")))')
```

If `zsh` is not finding `pip-review`, that probably means that the above directory is not included in your `PATH` environment variable, which you can check with the following command:

```sh
echo $PATH
```

If this is indeed the case, there are two possible solutions:

1. Use `python -m pip_review` instead of `pip-review`. This should always work regardless of what your `$PATH` looks like.
2. Add the directory to your `PATH` by including the following line in your `~/.profile` or `~/.zprofile`. This takes effect after you open a new terminal tab or window.

```profile
export PATH=$PATH:<the above path>
```

Please let me know whether this solves your problem.
